# Generated by Django 4.1 on 2022-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclasses',
            name='description',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
