# Generated by Django 4.1 on 2022-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_userclasses_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclasses',
            name='professor',
            field=models.CharField(max_length=200),
        ),
    ]
