# Generated by Django 4.1 on 2022-11-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_alter_userclasses_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclasses',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
