# Generated by Django 4.1.1 on 2022-10-11 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcome', '0004_rename_customuser_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('catalog_number', models.IntegerField()),
                ('component', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Classes',
            new_name='UserClasses',
        ),
    ]
