# Generated by Django 4.1.1 on 2022-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_class_rename_classes_userclasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.RemoveField(
            model_name='userclasses',
            name='classes',
        ),
        migrations.AddField(
            model_name='userclasses',
            name='catalog_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userclasses',
            name='component',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userclasses',
            name='subject',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
