# Generated by Django 4.2.dev20220917173820 on 2022-11-07 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcome', '0005_userclasses_search_class_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclasses',
            name='search_class',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Proffessor', models.CharField(max_length=150)),
                ('students', models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
