# Generated by Django 4.1.1 on 2022-10-11 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcome', '0006_delete_class_remove_userclasses_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclasses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
