# Generated by Django 4.1 on 2022-11-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_usertouserchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
