# Generated by Django 4.2.dev20220917173820 on 2022-11-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_alter_class_students'),
        ('welcome', '0008_friendlist_delete_userfriend'),
    ]

    operations = [
    ]
