# Generated by Django 4.1 on 2022-11-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_day_time'),
        ('welcome', '0009_delete_room'),
    ]

    operations = [
    ]
