# Generated by Django 4.1.3 on 2022-11-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_alter_meeting_date'),
        ('welcome', '0010_merge_0007_day_time_0009_delete_room'),
    ]

    operations = [
    ]
