# Generated by Django 4.2.dev20220917173820 on 2022-11-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_merge_0007_day_time_0009_delete_room'),
        ('welcome', '0013_alter_friendlist_user'),
    ]

    operations = [
    ]
